CREATE TABLE type_of_client(
    ID INTEGER NOT NULL PRIMARY KEY,
    TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE clients(
    ID VARCHAR(13) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONENUMBER VARCHAR(13) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TYPE INTEGER NOT NULL,
    FOREIGN KEY(TYPE) REFERENCES type_of_client(id)
);