CREATE TABLE neighborhoods(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(80) NOT NULL
);

CREATE TABLE type_of_property(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL
);

CREATE TABLE properties(
    ID SERIAL PRIMARY KEY,
    NEIGHBORHOOD INTEGER NOT NULL,
    TYPE INTEGER NOT NULL,
    CLIENT_OWNER VARCHAR(13) NOT NULL,
    OBSERVATIONS TEXT,
    FOREIGN KEY(NEIGHBORHOOD) REFERENCES neighborhoods(ID),
    FOREIGN KEY(TYPE) REFERENCES type_of_property(ID),
    FOREIGN KEY(CLIENT_OWNER) REFERENCES clients(ID)
);