CREATE TABLE offers(
    ID SERIAL PRIMARY KEY,
    PROPERTY_ID INTEGER NOT NULL,
    PRICE BIGINT NOT NULL,
    CREATION_DATE DATE NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    FOREIGN KEY(PROPERTY_ID) REFERENCES properties(ID)
);